sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION +test
scala: 2.12.3
jdk: oraclejdk8

