// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalabuff.proto

package scalabuff;

public final class Scalabuff {
  private Scalabuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(scalabuff.Scalabuff.scalaPackage);
    registry.add(scalabuff.Scalabuff.scalaOuterClassname);
  }
  public static final int SCALA_PACKAGE_FIELD_NUMBER = 1742;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> scalaPackage = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int SCALA_OUTER_CLASSNAME_FIELD_NUMBER = 1743;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> scalaOuterClassname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017scalabuff.proto\022\tscalabuff\032 google/pro" +
      "tobuf/descriptor.proto:4\n\rscala_package\022" +
      "\034.google.protobuf.FileOptions\030\316\r \001(\t:<\n\025" +
      "scala_outer_classname\022\034.google.protobuf." +
      "FileOptions\030\317\r \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          scalaPackage.internalInit(descriptor.getExtensions().get(0));
          scalaOuterClassname.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
